/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Affinity is a group of affinity scheduling rules.
 */
export interface AffinityV1 {
  /**
   * Node affinity is a group of node affinity scheduling rules.
   */
  nodeAffinity?: {
    [k: string]: any;
  } | null;
  /**
   * Pod affinity is a group of inter pod affinity scheduling rules.
   */
  podAffinity?: {
    [k: string]: any;
  } | null;
  /**
   * Pod anti affinity is a group of inter pod anti affinity scheduling rules.
   */
  podAntiAffinity?: {
    [k: string]: any;
  } | null;
}
