/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AllowedCSIDriver represents a single inline CSI Driver that is allowed to be used.
 */
export interface Allowedcsidriver {
  /**
   * Name is the registered name of the CSI driver
   */
  name: string | null;
}
