/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AllowedFlexVolume represents a single Flexvolume that is allowed to be used.
 */
export interface AllowedflexvolumePolicyV1Beta1 {
  /**
   * driver is the name of the Flexvolume driver.
   */
  driver: string | null;
}
