/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * APIServiceStatus contains derived information about an API server
 */
export interface Apiservicestatus {
  /**
   * Current service state of apiService.
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
}
