/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AuditSinkSpec holds the spec for the audit sink
 */
export interface AuditsinkspecAuditregistrationV1Alpha1 {
  /**
   * Policy defines the configuration of how audit events are logged
   */
  policy: {
    [k: string]: any;
  } | null;
  /**
   * Webhook holds the configuration of the webhook
   */
  webhook: {
    [k: string]: any;
  } | null;
}
