/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This information is immutable after the request is created. Only the Request and Usages fields can be set on creation, other fields are derived by Kubernetes and cannot be modified by users.
 */
export interface Certificatesigningrequestspec {
  /**
   * Extra information about the requesting user. See user.Info interface for details.
   */
  extra?: {
    [k: string]: any;
  } | null;
  /**
   * Group information about the requesting user. See user.Info interface for details.
   */
  groups?: (string | null)[];
  /**
   * Base64-encoded PKCS#10 CSR data
   */
  request: string | null;
  /**
   * UID information about the requesting user. See user.Info interface for details.
   */
  uid?: string | null;
  /**
   * allowedUsages specifies a set of usage contexts the key will be valid for. See: https://tools.ietf.org/html/rfc5280#section-4.2.1.3
   *      https://tools.ietf.org/html/rfc5280#section-4.2.1.12
   */
  usages?: (string | null)[];
  /**
   * Information about the requesting user. See user.Info interface for details.
   */
  username?: string | null;
}
