/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Information about the condition of a component.
 */
export interface ComponentconditionV1 {
  /**
   * Condition error code for a component. For example, a health check error code.
   */
  error?: string | null;
  /**
   * Message about the condition for a component. For example, information about a health check.
   */
  message?: string | null;
  /**
   * Status of the condition for a component. Valid values for "Healthy": "True", "False", or "Unknown".
   */
  status: string | null;
  /**
   * Type of condition for a component. Valid value: "Healthy"
   */
  type: string | null;
}
