/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Selects a key from a ConfigMap.
 */
export interface ConfigmapkeyselectorV1 {
  /**
   * The key to select.
   */
  key: string | null;
  /**
   * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   */
  name?: string | null;
  /**
   * Specify whether the ConfigMap or its key must be defined
   */
  optional?: boolean | null;
}
