/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ContainerStateTerminated is a terminated state of a container.
 */
export interface ContainerstateterminatedV1 {
  /**
   * Container's ID in the format 'docker://<container_id>'
   */
  containerID?: string | null;
  /**
   * Exit status from the last termination of the container
   */
  exitCode: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  finishedAt?: string | null;
  /**
   * Message regarding the last termination of the container
   */
  message?: string | null;
  /**
   * (brief) reason from the last termination of the container
   */
  reason?: string | null;
  /**
   * Signal from the last termination of the container
   */
  signal?: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  startedAt?: string | null;
}
