/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CronJobStatus represents the current state of a cron job.
 */
export interface CronjobstatusBatchV2Alpha1 {
  /**
   * A list of pointers to currently running jobs.
   */
  active?: ({
    [k: string]: any;
  } | null)[];
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastScheduleTime?: string | null;
}
