/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CronJobSpec describes how the job execution will look like and when it will actually run.
 */
export interface CronjobspecBatchV2Alpha1 {
  /**
   * Specifies how to treat concurrent executions of a Job. Valid values are: - "Allow" (default): allows CronJobs to run concurrently; - "Forbid": forbids concurrent runs, skipping next run if previous run hasn't finished yet; - "Replace": cancels currently running job and replaces it with a new one
   */
  concurrencyPolicy?: string | null;
  /**
   * The number of failed finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified.
   */
  failedJobsHistoryLimit?: number | null;
  /**
   * JobTemplateSpec describes the data a Job should have when created from a template
   */
  jobTemplate: {
    [k: string]: any;
  } | null;
  /**
   * The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
   */
  schedule: string | null;
  /**
   * Optional deadline in seconds for starting the job if it misses scheduled time for any reason.  Missed jobs executions will be counted as failed ones.
   */
  startingDeadlineSeconds?: number | null;
  /**
   * The number of successful finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified.
   */
  successfulJobsHistoryLimit?: number | null;
  /**
   * This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.  Defaults to false.
   */
  suspend?: boolean | null;
}
