/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CSINodeSpec holds information about the specification of all CSI drivers installed on a node
 */
export interface CsinodespecStorageV1Beta1 {
  /**
   * drivers is a list of information of all CSI Drivers existing on a node. If all drivers in the list are uninstalled, this can become empty.
   */
  drivers: ({
    [k: string]: any;
  } | null)[];
}
