/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a source location of a volume to mount, managed by an external CSI driver
 */
export interface Csivolumesource {
  /**
   * Driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
   */
  driver: string | null;
  /**
   * Filesystem type to mount. Ex. "ext4", "xfs", "ntfs". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply.
   */
  fsType?: string | null;
  /**
   * LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
   */
  nodePublishSecretRef?: {
    [k: string]: any;
  } | null;
  /**
   * Specifies a read-only configuration for the volume. Defaults to false (read/write).
   */
  readOnly?: boolean | null;
  /**
   * VolumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver's documentation for supported values.
   */
  volumeAttributes?: {
    [k: string]: any;
  } | null;
}
