/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CustomResourceDefinitionCondition contains details for the current condition of this pod.
 */
export interface CustomresourcedefinitionconditionApiextensionsV1Beta1 {
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastTransitionTime?: string | null;
  /**
   * message is a human-readable message indicating details about last transition.
   */
  message?: string | null;
  /**
   * reason is a unique, one-word, CamelCase reason for the condition's last transition.
   */
  reason?: string | null;
  /**
   * status is the status of the condition. Can be True, False, Unknown.
   */
  status: string | null;
  /**
   * type is the type of the condition. Types include Established, NamesAccepted and Terminating.
   */
  type: string | null;
}
