/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CustomResourceSubresources defines the status and scale subresources for CustomResources.
 */
export interface Customresourcesubresources {
  /**
   * CustomResourceSubresourceScale defines how to serve the scale subresource for CustomResources.
   */
  scale?: {
    [k: string]: any;
  } | null;
  /**
   * CustomResourceSubresourceStatus defines how to serve the status subresource for CustomResources. Status is represented by the `.status` JSON path inside of a CustomResource. When set, * exposes a /status subresource for the custom resource * PUT requests to the /status subresource take a custom resource object, and ignore changes to anything except the status stanza * PUT/POST/PATCH requests to the custom resource ignore changes to the status stanza
   */
  status?: {
    [k: string]: any;
  } | null;
}
