/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DaemonSetStatus represents the current status of a daemon set.
 */
export interface DaemonsetstatusAppsV1Beta2 {
  /**
   * Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.
   */
  collisionCount?: number | null;
  /**
   * Represents the latest available observations of a DaemonSet's current state.
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
   */
  currentNumberScheduled: number | null;
  /**
   * The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
   */
  desiredNumberScheduled: number | null;
  /**
   * The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds)
   */
  numberAvailable?: number | null;
  /**
   * The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
   */
  numberMisscheduled: number | null;
  /**
   * The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and ready.
   */
  numberReady: number | null;
  /**
   * The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds)
   */
  numberUnavailable?: number | null;
  /**
   * The most recent generation observed by the daemon set controller.
   */
  observedGeneration?: number | null;
  /**
   * The total number of nodes that are running updated daemon pod
   */
  updatedNumberScheduled?: number | null;
}
