/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DaemonEndpoint contains information about a single Daemon endpoint.
 */
export interface Daemonendpoint {
  /**
   * Port number of the given endpoint.
   */
  Port: number | null;
}
