/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DeploymentSpec is the specification of the desired behavior of the Deployment.
 */
export interface DeploymentspecExtensionsV1Beta1 {
  /**
   * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
   */
  minReadySeconds?: number | null;
  /**
   * Indicates that the deployment is paused and will not be processed by the deployment controller.
   */
  paused?: boolean | null;
  /**
   * The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. This is set to the max value of int32 (i.e. 2147483647) by default, which means "no deadline".
   */
  progressDeadlineSeconds?: number | null;
  /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
   */
  replicas?: number | null;
  /**
   * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. This is set to the max value of int32 (i.e. 2147483647) by default, which means "retaining all old RelicaSets".
   */
  revisionHistoryLimit?: number | null;
  /**
   * DEPRECATED.
   */
  rollbackTo?: {
    [k: string]: any;
  } | null;
  /**
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   */
  selector?: {
    [k: string]: any;
  } | null;
  /**
   * DeploymentStrategy describes how to replace existing pods with new ones.
   */
  strategy?: {
    [k: string]: any;
  } | null;
  /**
   * PodTemplateSpec describes the data a pod should have when created from a template
   */
  template: {
    [k: string]: any;
  } | null;
}
