/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DeploymentStatus is the most recently observed status of the Deployment.
 */
export interface DeploymentstatusAppsV1Beta1 {
  /**
   * Total number of available pods (ready for at least minReadySeconds) targeted by this deployment.
   */
  availableReplicas?: number | null;
  /**
   * Count of hash collisions for the Deployment. The Deployment controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ReplicaSet.
   */
  collisionCount?: number | null;
  /**
   * Represents the latest available observations of a deployment's current state.
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * The generation observed by the deployment controller.
   */
  observedGeneration?: number | null;
  /**
   * Total number of ready pods targeted by this deployment.
   */
  readyReplicas?: number | null;
  /**
   * Total number of non-terminated pods targeted by this deployment (their labels match the selector).
   */
  replicas?: number | null;
  /**
   * Total number of unavailable pods targeted by this deployment. This is the total number of pods that are still required for the deployment to have 100% available capacity. They may either be pods that are running but not yet available or pods that still have not been created.
   */
  unavailableReplicas?: number | null;
  /**
   * Total number of non-terminated pods targeted by this deployment that have the desired template spec.
   */
  updatedReplicas?: number | null;
}
