/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DEPRECATED. DeploymentRollback stores the information required to rollback a deployment.
 */
export interface DeploymentrollbackExtensionsV1Beta1 {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: "extensions/v1beta1";
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: "DeploymentRollback";
  /**
   * Required: This must match the Name of a deployment.
   */
  name: string | null;
  /**
   * DEPRECATED.
   */
  rollbackTo: {
    [k: string]: any;
  } | null;
  /**
   * The annotations to be updated to a deployment
   */
  updatedAnnotations?: {
    [k: string]: any;
  } | null;
}
