/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Endpoint represents a single logical "backend" implementing a service.
 */
export interface Endpoint {
  /**
   * addresses of this endpoint. The contents of this field are interpreted according to the corresponding EndpointSlice addressType field. This allows for cases like dual-stack (IPv4 and IPv6) networking. Consumers (e.g. kube-proxy) must handle different types of addresses in the context of their own capabilities. This must contain at least one address but no more than 100.
   */
  addresses: (string | null)[];
  /**
   * EndpointConditions represents the current condition of an endpoint.
   */
  conditions?: {
    [k: string]: any;
  } | null;
  /**
   * hostname of this endpoint. This field may be used by consumers of endpoints to distinguish endpoints from each other (e.g. in DNS names). Multiple endpoints which use the same hostname should be considered fungible (e.g. multiple A values in DNS). Must pass DNS Label (RFC 1123) validation.
   */
  hostname?: string | null;
  /**
   * ObjectReference contains enough information to let you inspect or modify the referred object.
   */
  targetRef?: {
    [k: string]: any;
  } | null;
  /**
   * topology contains arbitrary topology information associated with the endpoint. These key/value pairs must conform with the label format. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels Topology may include a maximum of 16 key/value pairs. This includes, but is not limited to the following well known keys: * kubernetes.io/hostname: the value indicates the hostname of the node
   *   where the endpoint is located. This should match the corresponding
   *   node label.
   * * topology.kubernetes.io/zone: the value indicates the zone where the
   *   endpoint is located. This should match the corresponding node label.
   * * topology.kubernetes.io/region: the value indicates the region where the
   *   endpoint is located. This should match the corresponding node label.
   */
  topology?: {
    [k: string]: any;
  } | null;
}
