/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EndpointAddress is a tuple that describes single IP address.
 */
export interface Endpointaddress {
  /**
   * The Hostname of this endpoint
   */
  hostname?: string | null;
  /**
   * The IP of this endpoint. May not be loopback (127.0.0.0/8), link-local (169.254.0.0/16), or link-local multicast ((224.0.0.0/24). IPv6 is also accepted but not fully supported on all platforms. Also, certain kubernetes components, like kube-proxy, are not IPv6 ready.
   */
  ip: string | null;
  /**
   * Optional: Node hosting this endpoint. This can be used to determine endpoints local to a node.
   */
  nodeName?: string | null;
  /**
   * ObjectReference contains enough information to let you inspect or modify the referred object.
   */
  targetRef?: {
    [k: string]: any;
  } | null;
}
