/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EnvFromSource represents the source of a set of ConfigMaps
 */
export interface EnvfromsourceV1 {
  /**
   * ConfigMapEnvSource selects a ConfigMap to populate the environment variables with.
   *
   * The contents of the target ConfigMap's Data field will represent the key-value pairs as environment variables.
   */
  configMapRef?: {
    [k: string]: any;
  } | null;
  /**
   * An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
   */
  prefix?: string | null;
  /**
   * SecretEnvSource selects a Secret to populate the environment variables with.
   *
   * The contents of the target Secret's Data field will represent the key-value pairs as environment variables.
   */
  secretRef?: {
    [k: string]: any;
  } | null;
}
