/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EventSource contains information for an event.
 */
export interface EventsourceV1 {
  /**
   * Component from which the event is generated.
   */
  component?: string | null;
  /**
   * Node name on which the event is generated.
   */
  host?: string | null;
}
