/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event is a report of an event somewhere in the cluster. It generally denotes some state change in the system.
 */
export interface EventEventsV1Beta1 {
  /**
   * What action was taken/failed regarding to the regarding object.
   */
  action?: string | null;
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: "events.k8s.io/v1beta1";
  /**
   * Deprecated field assuring backward compatibility with core.v1 Event type
   */
  deprecatedCount?: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  deprecatedFirstTimestamp?: string | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  deprecatedLastTimestamp?: string | null;
  /**
   * EventSource contains information for an event.
   */
  deprecatedSource?: {
    [k: string]: any;
  } | null;
  /**
   * MicroTime is version of Time with microsecond level precision.
   */
  eventTime: string | null;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: "Event";
  /**
   * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
   */
  metadata?: {
    [k: string]: any;
  } | null;
  /**
   * Optional. A human-readable description of the status of this operation. Maximal length of the note is 1kB, but libraries should be prepared to handle values up to 64kB.
   */
  note?: string | null;
  /**
   * Why the action was taken.
   */
  reason?: string | null;
  /**
   * ObjectReference contains enough information to let you inspect or modify the referred object.
   */
  regarding?: {
    [k: string]: any;
  } | null;
  /**
   * ObjectReference contains enough information to let you inspect or modify the referred object.
   */
  related?: {
    [k: string]: any;
  } | null;
  /**
   * Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`.
   */
  reportingController?: string | null;
  /**
   * ID of the controller instance, e.g. `kubelet-xyzf`.
   */
  reportingInstance?: string | null;
  /**
   * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
   */
  series?: {
    [k: string]: any;
  } | null;
  /**
   * Type of this event (Normal, Warning), new types could be added in the future.
   */
  type?: string | null;
}
