/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 */
export interface EventseriesEventsV1Beta1 {
  /**
   * Number of occurrences in this series up to the last heartbeat time
   */
  count: number | null;
  /**
   * MicroTime is version of Time with microsecond level precision.
   */
  lastObservedTime: string | null;
  /**
   * Information whether this series is ongoing or finished. Deprecated. Planned removal for 1.18
   */
  state: string | null;
}
