/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ExternalDocumentation allows referencing an external resource for extended documentation.
 */
export interface ExternaldocumentationApiextensionsV1 {
  description?: string | null;
  url?: string | null;
}
