/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
 */
export interface Externalmetricstatus {
  /**
   * MetricValueStatus holds the current value for a metric
   */
  current: {
    [k: string]: any;
  } | null;
  /**
   * MetricIdentifier defines the name and optionally selector for a metric
   */
  metric: {
    [k: string]: any;
  } | null;
}
