/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
 */
export interface ExternalmetricstatusAutoscalingV2Beta1 {
  currentAverageValue?: (string | null) | (number | null);
  currentValue: (string | null) | (number | null);
  /**
   * metricName is the name of a metric used for autoscaling in metric system.
   */
  metricName: string | null;
  /**
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   */
  metricSelector?: {
    [k: string]: any;
  } | null;
}
