/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster). Exactly one "target" type should be set.
 */
export interface ExternalmetricsourceAutoscalingV2Beta1 {
  /**
   * metricName is the name of the metric in question.
   */
  metricName: string | null;
  /**
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   */
  metricSelector?: {
    [k: string]: any;
  } | null;
  targetAverageValue?: (string | null) | (number | null);
  targetValue?: (string | null) | (number | null);
}
