/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GroupVersion contains the "group/version" and "version" string of a version. It is made a struct to keep extensibility.
 */
export interface Groupversionfordiscovery {
  /**
   * groupVersion specifies the API group and version in the form "group/version"
   */
  groupVersion: string | null;
  /**
   * version specifies the version in the form of "version". This is to save the clients the trouble of splitting the GroupVersion.
   */
  version: string | null;
}
