/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Handler defines a specific action that should be taken
 */
export interface HandlerV1 {
  /**
   * ExecAction describes a "run in container" action.
   */
  exec?: {
    [k: string]: any;
  } | null;
  /**
   * HTTPGetAction describes an action based on HTTP Get requests.
   */
  httpGet?: {
    [k: string]: any;
  } | null;
  /**
   * TCPSocketAction describes an action based on opening a socket
   */
  tcpSocket?: {
    [k: string]: any;
  } | null;
}
