/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * current status of a horizontal pod autoscaler
 */
export interface HorizontalpodautoscalerstatusAutoscalingV1 {
  /**
   * current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.
   */
  currentCPUUtilizationPercentage?: number | null;
  /**
   * current number of replicas of pods managed by this autoscaler.
   */
  currentReplicas: number | null;
  /**
   * desired number of replicas of pods managed by this autoscaler.
   */
  desiredReplicas: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastScaleTime?: string | null;
  /**
   * most recent generation observed by this autoscaler.
   */
  observedGeneration?: number | null;
}
