/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 */
export interface HttpheaderV1 {
  /**
   * The header field name
   */
  name: string | null;
  /**
   * The header field value
   */
  value: string | null;
}
