/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * IDRange provides a min/max of an allowed range of IDs.
 */
export interface IdrangePolicyV1Beta1 {
  /**
   * max is the end of the range, inclusive.
   */
  max: number | null;
  /**
   * min is the start of the range, inclusive.
   */
  min: number | null;
}
