/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Info contains versioning information. how we'll want to distribute that information.
 */
export interface InfoPkgVersion {
  buildDate: string | null;
  compiler: string | null;
  gitCommit: string | null;
  gitTreeState: string | null;
  gitVersion: string | null;
  goVersion: string | null;
  major: string | null;
  minor: string | null;
  platform: string | null;
}
