/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JobStatus represents the current state of a Job.
 */
export interface JobstatusBatchV1 {
  /**
   * The number of actively running pods.
   */
  active?: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  completionTime?: string | null;
  /**
   * The latest available observations of an object's current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * The number of pods which reached phase Failed.
   */
  failed?: number | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  startTime?: string | null;
  /**
   * The number of pods which reached phase Succeeded.
   */
  succeeded?: number | null;
}
