/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JobTemplateSpec describes the data a Job should have when created from a template
 */
export interface JobtemplatespecBatchV2Alpha1 {
  /**
   * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
   */
  metadata?: {
    [k: string]: any;
  } | null;
  /**
   * JobSpec describes how the job execution will look like.
   */
  spec?: {
    [k: string]: any;
  } | null;
}
