/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * LeaseSpec is a specification of a Lease.
 */
export interface LeasespecCoordinationV1 {
  /**
   * MicroTime is version of Time with microsecond level precision.
   */
  acquireTime?: string | null;
  /**
   * holderIdentity contains the identity of the holder of a current lease.
   */
  holderIdentity?: string | null;
  /**
   * leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measure against time of last observed RenewTime.
   */
  leaseDurationSeconds?: number | null;
  /**
   * leaseTransitions is the number of transitions of a lease between holders.
   */
  leaseTransitions?: number | null;
  /**
   * MicroTime is version of Time with microsecond level precision.
   */
  renewTime?: string | null;
}
