/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
 */
export interface Lifecycle {
  /**
   * Handler defines a specific action that should be taken
   */
  postStart?: {
    [k: string]: any;
  } | null;
  /**
   * Handler defines a specific action that should be taken
   */
  preStop?: {
    [k: string]: any;
  } | null;
}
