/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * LimitRangeSpec defines a min/max usage limit for resources that match on kind.
 */
export interface LimitrangespecV1 {
  /**
   * Limits is the list of LimitRangeItem objects that are enforced.
   */
  limits: ({
    [k: string]: any;
  } | null)[];
}
