/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
 */
export interface LimitrangeitemV1 {
  /**
   * Default resource requirement limit value by resource name if resource limit is omitted.
   */
  default?: {
    [k: string]: any;
  } | null;
  /**
   * DefaultRequest is the default resource requirement request value by resource name if resource request is omitted.
   */
  defaultRequest?: {
    [k: string]: any;
  } | null;
  /**
   * Max usage constraints on this kind by resource name.
   */
  max?: {
    [k: string]: any;
  } | null;
  /**
   * MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource.
   */
  maxLimitRequestRatio?: {
    [k: string]: any;
  } | null;
  /**
   * Min usage constraints on this kind by resource name.
   */
  min?: {
    [k: string]: any;
  } | null;
  /**
   * Type of resource that this limit applies to.
   */
  type?: string | null;
}
