/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * MetricValueStatus holds the current value for a metric
 */
export interface MetricvaluestatusAutoscalingV2Beta2 {
  /**
   * currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
   */
  averageUtilization?: number | null;
  averageValue?: (string | null) | (number | null);
  value?: (string | null) | (number | null);
}
