/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NamespaceCondition contains details about state of namespace.
 */
export interface Namespacecondition {
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastTransitionTime?: string | null;
  message?: string | null;
  reason?: string | null;
  /**
   * Status of the condition, one of True, False, Unknown.
   */
  status: string | null;
  /**
   * Type of namespace controller condition.
   */
  type: string | null;
}
