/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 */
export interface Nodeselectorterm {
  /**
   * A list of node selector requirements by node's labels.
   */
  matchExpressions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * A list of node selector requirements by node's fields.
   */
  matchFields?: ({
    [k: string]: any;
  } | null)[];
}
