/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeStatus is information about the current status of a node.
 */
export interface Nodestatus {
  /**
   * List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses Note: This field is declared as mergeable, but the merge key is not sufficiently unique, which can cause data corruption when it is merged. Callers should instead use a full-replacement patch. See http://pr.k8s.io/79391 for an example.
   */
  addresses?: ({
    [k: string]: any;
  } | null)[];
  /**
   * Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.
   */
  allocatable?: {
    [k: string]: any;
  } | null;
  /**
   * Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity
   */
  capacity?: {
    [k: string]: any;
  } | null;
  /**
   * Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/concepts/nodes/node/#condition
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * NodeConfigStatus describes the status of the config assigned by Node.Spec.ConfigSource.
   */
  config?: {
    [k: string]: any;
  } | null;
  /**
   * NodeDaemonEndpoints lists ports opened by daemons running on the Node.
   */
  daemonEndpoints?: {
    [k: string]: any;
  } | null;
  /**
   * List of container images on this node
   */
  images?: ({
    [k: string]: any;
  } | null)[];
  /**
   * NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
   */
  nodeInfo?: {
    [k: string]: any;
  } | null;
  /**
   * NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated.
   */
  phase?: string | null;
  /**
   * List of volumes that are attached to the node.
   */
  volumesAttached?: ({
    [k: string]: any;
  } | null)[];
  /**
   * List of attachable volumes in use (mounted) by the node.
   */
  volumesInUse?: (string | null)[];
}
