/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeDaemonEndpoints lists ports opened by daemons running on the Node.
 */
export interface Nodedaemonendpoints {
  /**
   * DaemonEndpoint contains information about a single Daemon endpoint.
   */
  kubeletEndpoint?: {
    [k: string]: any;
  } | null;
}
