/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil.
 */
export interface Nodeconfigsource {
  /**
   * ConfigMapNodeConfigSource contains the information to reference a ConfigMap as a config source for the Node.
   */
  configMap?: {
    [k: string]: any;
  } | null;
}
