/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
 */
export interface Nodesysteminfo {
  /**
   * The Architecture reported by the node
   */
  architecture: string | null;
  /**
   * Boot ID reported by the node.
   */
  bootID: string | null;
  /**
   * ContainerRuntime Version reported by the node through runtime remote API (e.g. docker://1.5.0).
   */
  containerRuntimeVersion: string | null;
  /**
   * Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64).
   */
  kernelVersion: string | null;
  /**
   * KubeProxy Version reported by the node.
   */
  kubeProxyVersion: string | null;
  /**
   * Kubelet Version reported by the node.
   */
  kubeletVersion: string | null;
  /**
   * MachineID reported by the node. For unique machine identification in the cluster this field is preferred. Learn more from man(5) machine-id: http://man7.org/linux/man-pages/man5/machine-id.5.html
   */
  machineID: string | null;
  /**
   * The Operating System reported by the node
   */
  operatingSystem: string | null;
  /**
   * OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy)).
   */
  osImage: string | null;
  /**
   * SystemUUID reported by the node. For unique machine identification MachineID is preferred. This field is specific to Red Hat hosts https://access.redhat.com/documentation/en-US/Red_Hat_Subscription_Management/1/html/RHSM/getting-system-uuid.html
   */
  systemUUID: string | null;
}
