/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeCondition contains condition information for a node.
 */
export interface Nodecondition {
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastHeartbeatTime?: string | null;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  lastTransitionTime?: string | null;
  /**
   * Human readable message indicating details about last transition.
   */
  message?: string | null;
  /**
   * (brief) reason for the condition's last transition.
   */
  reason?: string | null;
  /**
   * Status of the condition, one of True, False, Unknown.
   */
  status: string | null;
  /**
   * Type of node condition.
   */
  type: string | null;
}
