/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NodeSpec describes the attributes that a node is created with.
 */
export interface NodespecV1 {
  /**
   * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil.
   */
  configSource?: {
    [k: string]: any;
  } | null;
  /**
   * Deprecated. Not all kubelets will set this field. Remove field after 1.13. see: https://issues.k8s.io/61966
   */
  externalID?: string | null;
  /**
   * PodCIDR represents the pod IP range assigned to the node.
   */
  podCIDR?: string | null;
  /**
   * podCIDRs represents the IP ranges assigned to the node for usage by Pods on that node. If this field is specified, the 0th entry must match the podCIDR field. It may contain at most 1 value for each of IPv4 and IPv6.
   */
  podCIDRs?: (string | null)[];
  /**
   * ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
   */
  providerID?: string | null;
  /**
   * If specified, the node's taints.
   */
  taints?: ({
    [k: string]: any;
  } | null)[];
  /**
   * Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration
   */
  unschedulable?: boolean | null;
}
