/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NonResourceAttributes includes the authorization attributes available for non-resource requests to the Authorizer interface
 */
export interface Nonresourceattributes {
  /**
   * Path is the URL path of the request
   */
  path?: string | null;
  /**
   * Verb is the standard HTTP verb
   */
  verb?: string | null;
}
