/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 */
export interface ObjectmetricstatusAutoscalingV2Beta1 {
  averageValue?: (string | null) | (number | null);
  currentValue: (string | null) | (number | null);
  /**
   * metricName is the name of the metric in question.
   */
  metricName: string | null;
  /**
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   */
  selector?: {
    [k: string]: any;
  } | null;
  /**
   * CrossVersionObjectReference contains enough information to let you identify the referred resource.
   */
  target: {
    [k: string]: any;
  } | null;
}
