/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 */
export interface ObjectmetricstatusAutoscalingV2Beta2 {
  /**
   * MetricValueStatus holds the current value for a metric
   */
  current: {
    [k: string]: any;
  } | null;
  /**
   * CrossVersionObjectReference contains enough information to let you identify the referred resource.
   */
  describedObject: {
    [k: string]: any;
  } | null;
  /**
   * MetricIdentifier defines the name and optionally selector for a metric
   */
  metric: {
    [k: string]: any;
  } | null;
}
