/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 */
export interface Objectmetricsource {
  /**
   * CrossVersionObjectReference contains enough information to let you identify the referred resource.
   */
  describedObject: {
    [k: string]: any;
  } | null;
  /**
   * MetricIdentifier defines the name and optionally selector for a metric
   */
  metric: {
    [k: string]: any;
  } | null;
  /**
   * MetricTarget defines the target value, average value, or average utilization of a specific metric
   */
  target: {
    [k: string]: any;
  } | null;
}
