/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Overhead structure represents the resource overhead associated with running a pod.
 */
export interface OverheadNodeV1Alpha1 {
  /**
   * PodFixed represents the fixed resource overhead associated with running a pod.
   */
  podFixed?: {
    [k: string]: any;
  } | null;
}
