/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes
 */
export interface Persistentvolumeclaimspec {
  /**
   * AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
   */
  accessModes?: (string | null)[];
  /**
   * TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace.
   */
  dataSource?: {
    [k: string]: any;
  } | null;
  /**
   * ResourceRequirements describes the compute resource requirements.
   */
  resources?: {
    [k: string]: any;
  } | null;
  /**
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   */
  selector?: {
    [k: string]: any;
  } | null;
  /**
   * Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
   */
  storageClassName?: string | null;
  /**
   * volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec. This is a beta feature.
   */
  volumeMode?: string | null;
  /**
   * VolumeName is the binding reference to the PersistentVolume backing this claim.
   */
  volumeName?: string | null;
}
