/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PersistentVolumeSpec is the specification of a persistent volume.
 */
export interface Persistentvolumespec {
  /**
   * AccessModes contains all ways the volume can be mounted. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes
   */
  accessModes?: (string | null)[];
  /**
   * Represents a Persistent Disk resource in AWS.
   *
   * An AWS EBS disk must exist before mounting to a container. The disk must also be in the same AWS zone as the kubelet. An AWS EBS disk can only be mounted as read/write once. AWS EBS volumes support ownership management and SELinux relabeling.
   */
  awsElasticBlockStore?: {
    [k: string]: any;
  } | null;
  /**
   * AzureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
   */
  azureDisk?: {
    [k: string]: any;
  } | null;
  /**
   * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
   */
  azureFile?: {
    [k: string]: any;
  } | null;
  /**
   * A description of the persistent volume's resources and capacity. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity
   */
  capacity?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Ceph Filesystem mount that lasts the lifetime of a pod Cephfs volumes do not support ownership management or SELinux relabeling.
   */
  cephfs?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a cinder volume resource in Openstack. A Cinder volume must exist before mounting to a container. The volume must also be in the same region as the kubelet. Cinder volumes support ownership management and SELinux relabeling.
   */
  cinder?: {
    [k: string]: any;
  } | null;
  /**
   * ObjectReference contains enough information to let you inspect or modify the referred object.
   */
  claimRef?: {
    [k: string]: any;
  } | null;
  /**
   * Represents storage that is managed by an external CSI volume driver (Beta feature)
   */
  csi?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Fibre Channel volume. Fibre Channel volumes can only be mounted as read/write once. Fibre Channel volumes support ownership management and SELinux relabeling.
   */
  fc?: {
    [k: string]: any;
  } | null;
  /**
   * FlexPersistentVolumeSource represents a generic persistent volume resource that is provisioned/attached using an exec based plugin.
   */
  flexVolume?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Flocker volume mounted by the Flocker agent. One and only one of datasetName and datasetUUID should be set. Flocker volumes do not support ownership management or SELinux relabeling.
   */
  flocker?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Persistent Disk resource in Google Compute Engine.
   *
   * A GCE PD must exist before mounting to a container. The disk must also be in the same GCE project and zone as the kubelet. A GCE PD can only be mounted as read/write once or read-only many times. GCE PDs support ownership management and SELinux relabeling.
   */
  gcePersistentDisk?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs volumes do not support ownership management or SELinux relabeling.
   */
  glusterfs?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a host path mapped into a pod. Host path volumes do not support ownership management or SELinux relabeling.
   */
  hostPath?: {
    [k: string]: any;
  } | null;
  /**
   * ISCSIPersistentVolumeSource represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.
   */
  iscsi?: {
    [k: string]: any;
  } | null;
  /**
   * Local represents directly-attached storage with node affinity (Beta feature)
   */
  local?: {
    [k: string]: any;
  } | null;
  /**
   * A list of mount options, e.g. ["ro", "soft"]. Not validated - mount will simply fail if one is invalid. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options
   */
  mountOptions?: (string | null)[];
  /**
   * Represents an NFS mount that lasts the lifetime of a pod. NFS volumes do not support ownership management or SELinux relabeling.
   */
  nfs?: {
    [k: string]: any;
  } | null;
  /**
   * VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
   */
  nodeAffinity?: {
    [k: string]: any;
  } | null;
  /**
   * What happens to a persistent volume when released from its claim. Valid options are Retain (default for manually created PersistentVolumes), Delete (default for dynamically provisioned PersistentVolumes), and Recycle (deprecated). Recycle must be supported by the volume plugin underlying this PersistentVolume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming
   */
  persistentVolumeReclaimPolicy?: string | null;
  /**
   * Represents a Photon Controller persistent disk resource.
   */
  photonPersistentDisk?: {
    [k: string]: any;
  } | null;
  /**
   * PortworxVolumeSource represents a Portworx volume resource.
   */
  portworxVolume?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Quobyte mount that lasts the lifetime of a pod. Quobyte volumes do not support ownership management or SELinux relabeling.
   */
  quobyte?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Rados Block Device mount that lasts the lifetime of a pod. RBD volumes support ownership management and SELinux relabeling.
   */
  rbd?: {
    [k: string]: any;
  } | null;
  /**
   * ScaleIOPersistentVolumeSource represents a persistent ScaleIO volume
   */
  scaleIO?: {
    [k: string]: any;
  } | null;
  /**
   * Name of StorageClass to which this persistent volume belongs. Empty value means that this volume does not belong to any StorageClass.
   */
  storageClassName?: string | null;
  /**
   * Represents a StorageOS persistent volume resource.
   */
  storageos?: {
    [k: string]: any;
  } | null;
  /**
   * volumeMode defines if a volume is intended to be used with a formatted filesystem or to remain in raw block state. Value of Filesystem is implied when not included in spec. This is a beta feature.
   */
  volumeMode?: string | null;
  /**
   * Represents a vSphere volume resource.
   */
  vsphereVolume?: {
    [k: string]: any;
  } | null;
}
