/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PersistentVolumeClaimStatus is the current status of a persistent volume claim.
 */
export interface PersistentvolumeclaimstatusV1 {
  /**
   * AccessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
   */
  accessModes?: (string | null)[];
  /**
   * Represents the actual resources of the underlying volume.
   */
  capacity?: {
    [k: string]: any;
  } | null;
  /**
   * Current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to 'ResizeStarted'.
   */
  conditions?: ({
    [k: string]: any;
  } | null)[];
  /**
   * Phase represents the current phase of PersistentVolumeClaim.
   */
  phase?: string | null;
}
