/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.
 */
export interface PoddisruptionbudgetstatusPolicyV1Beta1 {
  /**
   * current number of healthy pods
   */
  currentHealthy: number | null;
  /**
   * minimum desired number of healthy pods
   */
  desiredHealthy: number | null;
  /**
   * DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn't occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions.
   */
  disruptedPods?: {
    [k: string]: any;
  } | null;
  /**
   * Number of pod disruptions that are currently allowed.
   */
  disruptionsAllowed: number | null;
  /**
   * total number of pods counted by this disruption budget
   */
  expectedPods: number | null;
  /**
   * Most recent generation observed when updating this PDB status. PodDisruptionsAllowed and other status informatio is valid only if observedGeneration equals to PDB's object generation.
   */
  observedGeneration?: number | null;
}
