/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 */
export interface PoddnsconfigoptionV1 {
  /**
   * Required.
   */
  name?: string | null;
  value?: string | null;
}
