/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodReadinessGate contains the reference to a pod condition
 */
export interface Podreadinessgate {
  /**
   * ConditionType refers to a condition in the pod's condition list with matching type.
   */
  conditionType: string | null;
}
