/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodSecurityPolicySpec defines the policy enforced.
 */
export interface PodsecuritypolicyspecPolicyV1Beta1 {
  /**
   * allowPrivilegeEscalation determines if a pod can request to allow privilege escalation. If unspecified, defaults to true.
   */
  allowPrivilegeEscalation?: boolean | null;
  /**
   * AllowedCSIDrivers is a whitelist of inline CSI drivers that must be explicitly set to be embedded within a pod spec. An empty value indicates that any CSI driver can be used for inline ephemeral volumes. This is an alpha field, and is only honored if the API server enables the CSIInlineVolume feature gate.
   */
  allowedCSIDrivers?: ({
    [k: string]: any;
  } | null)[];
  /**
   * allowedCapabilities is a list of capabilities that can be requested to add to the container. Capabilities in this field may be added at the pod author's discretion. You must not list a capability in both allowedCapabilities and requiredDropCapabilities.
   */
  allowedCapabilities?: (string | null)[];
  /**
   * allowedFlexVolumes is a whitelist of allowed Flexvolumes.  Empty or nil indicates that all Flexvolumes may be used.  This parameter is effective only when the usage of the Flexvolumes is allowed in the "volumes" field.
   */
  allowedFlexVolumes?: ({
    [k: string]: any;
  } | null)[];
  /**
   * allowedHostPaths is a white list of allowed host paths. Empty indicates that all host paths may be used.
   */
  allowedHostPaths?: ({
    [k: string]: any;
  } | null)[];
  /**
   * AllowedProcMountTypes is a whitelist of allowed ProcMountTypes. Empty or nil indicates that only the DefaultProcMountType may be used. This requires the ProcMountType feature flag to be enabled.
   */
  allowedProcMountTypes?: (string | null)[];
  /**
   * allowedUnsafeSysctls is a list of explicitly allowed unsafe sysctls, defaults to none. Each entry is either a plain sysctl name or ends in "*" in which case it is considered as a prefix of allowed sysctls. Single * means all unsafe sysctls are allowed. Kubelet has to whitelist all allowed unsafe sysctls explicitly to avoid rejection.
   *
   * Examples: e.g. "foo/*" allows "foo/bar", "foo/baz", etc. e.g. "foo.*" allows "foo.bar", "foo.baz", etc.
   */
  allowedUnsafeSysctls?: (string | null)[];
  /**
   * defaultAddCapabilities is the default set of capabilities that will be added to the container unless the pod spec specifically drops the capability.  You may not list a capability in both defaultAddCapabilities and requiredDropCapabilities. Capabilities added here are implicitly allowed, and need not be included in the allowedCapabilities list.
   */
  defaultAddCapabilities?: (string | null)[];
  /**
   * defaultAllowPrivilegeEscalation controls the default setting for whether a process can gain more privileges than its parent process.
   */
  defaultAllowPrivilegeEscalation?: boolean | null;
  /**
   * forbiddenSysctls is a list of explicitly forbidden sysctls, defaults to none. Each entry is either a plain sysctl name or ends in "*" in which case it is considered as a prefix of forbidden sysctls. Single * means all sysctls are forbidden.
   *
   * Examples: e.g. "foo/*" forbids "foo/bar", "foo/baz", etc. e.g. "foo.*" forbids "foo.bar", "foo.baz", etc.
   */
  forbiddenSysctls?: (string | null)[];
  /**
   * FSGroupStrategyOptions defines the strategy type and options used to create the strategy.
   */
  fsGroup: {
    [k: string]: any;
  } | null;
  /**
   * hostIPC determines if the policy allows the use of HostIPC in the pod spec.
   */
  hostIPC?: boolean | null;
  /**
   * hostNetwork determines if the policy allows the use of HostNetwork in the pod spec.
   */
  hostNetwork?: boolean | null;
  /**
   * hostPID determines if the policy allows the use of HostPID in the pod spec.
   */
  hostPID?: boolean | null;
  /**
   * hostPorts determines which host port ranges are allowed to be exposed.
   */
  hostPorts?: ({
    [k: string]: any;
  } | null)[];
  /**
   * privileged determines if a pod can request to be run as privileged.
   */
  privileged?: boolean | null;
  /**
   * readOnlyRootFilesystem when set to true will force containers to run with a read only root file system.  If the container specifically requests to run with a non-read only root file system the PSP should deny the pod. If set to false the container may run with a read only root file system if it wishes but it will not be forced to.
   */
  readOnlyRootFilesystem?: boolean | null;
  /**
   * requiredDropCapabilities are the capabilities that will be dropped from the container.  These are required to be dropped and cannot be added.
   */
  requiredDropCapabilities?: (string | null)[];
  /**
   * RunAsGroupStrategyOptions defines the strategy type and any options used to create the strategy.
   */
  runAsGroup?: {
    [k: string]: any;
  } | null;
  /**
   * RunAsUserStrategyOptions defines the strategy type and any options used to create the strategy.
   */
  runAsUser: {
    [k: string]: any;
  } | null;
  /**
   * RuntimeClassStrategyOptions define the strategy that will dictate the allowable RuntimeClasses for a pod.
   */
  runtimeClass?: {
    [k: string]: any;
  } | null;
  /**
   * SELinuxStrategyOptions defines the strategy type and any options used to create the strategy.
   */
  seLinux: {
    [k: string]: any;
  } | null;
  /**
   * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
   */
  supplementalGroups: {
    [k: string]: any;
  } | null;
  /**
   * volumes is a white list of allowed volume plugins. Empty indicates that no volumes may be used. To allow all volumes you may use '*'.
   */
  volumes?: (string | null)[];
}
