/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
 */
export interface PodsmetricsourceAutoscalingV2Beta2 {
  /**
   * MetricIdentifier defines the name and optionally selector for a metric
   */
  metric: {
    [k: string]: any;
  } | null;
  /**
   * MetricTarget defines the target value, average value, or average utilization of a specific metric
   */
  target: {
    [k: string]: any;
  } | null;
}
