/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
 */
export interface PodsmetricstatusAutoscalingV2Beta2 {
  /**
   * MetricValueStatus holds the current value for a metric
   */
  current: {
    [k: string]: any;
  } | null;
  /**
   * MetricIdentifier defines the name and optionally selector for a metric
   */
  metric: {
    [k: string]: any;
  } | null;
}
