/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PodTemplateSpec describes the data a pod should have when created from a template
 */
export interface PodtemplatespecV1 {
  /**
   * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
   */
  metadata?: {
    [k: string]: any;
  } | null;
  /**
   * PodSpec is a description of a pod.
   */
  spec?: {
    [k: string]: any;
  } | null;
}
