/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
 */
export interface PreconditionsMetaV1 {
  /**
   * Specifies the target ResourceVersion
   */
  resourceVersion?: string | null;
  /**
   * Specifies the target UID.
   */
  uid?: string | null;
}
