/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceAttributes includes the authorization attributes available for resource requests to the Authorizer interface
 */
export interface ResourceattributesAuthorizationV1Beta1 {
  /**
   * Group is the API Group of the Resource.  "*" means all.
   */
  group?: string | null;
  /**
   * Name is the name of the resource being requested for a "get" or deleted for a "delete". "" (empty) means all.
   */
  name?: string | null;
  /**
   * Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces "" (empty) is defaulted for LocalSubjectAccessReviews "" (empty) is empty for cluster-scoped resources "" (empty) means "all" for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview
   */
  namespace?: string | null;
  /**
   * Resource is one of the existing resource types.  "*" means all.
   */
  resource?: string | null;
  /**
   * Subresource is one of the existing resource types.  "" means none.
   */
  subresource?: string | null;
  /**
   * Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  "*" means all.
   */
  verb?: string | null;
  /**
   * Version is the API Version of the Resource.  "*" means all.
   */
  version?: string | null;
}
