/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceRule is the list of actions the subject is allowed to perform on resources. The list ordering isn't significant, may contain duplicates, and possibly be incomplete.
 */
export interface ResourceruleAuthorizationV1 {
  /**
   * APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of the enumerated resources in any API group will be allowed.  "*" means all.
   */
  apiGroups?: (string | null)[];
  /**
   * ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.  "*" means all.
   */
  resourceNames?: (string | null)[];
  /**
   * Resources is a list of resources this rule applies to.  "*" means all in the specified apiGroups.
   *  "* /foo" represents the subresource 'foo' for all resources in the specified apiGroups.
   */
  resources?: (string | null)[];
  /**
   * Verb is a list of kubernetes resource API verbs, like: get, list, watch, create, update, delete, proxy.  "*" means all.
   */
  verbs: (string | null)[];
}
