/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceQuotaStatus defines the enforced hard limits and observed use.
 */
export interface Resourcequotastatus {
  /**
   * Hard is the set of enforced hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/
   */
  hard?: {
    [k: string]: any;
  } | null;
  /**
   * Used is the current observed total usage of the resource in the namespace.
   */
  used?: {
    [k: string]: any;
  } | null;
}
