/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.  Only one "target" type should be set.
 */
export interface ResourcemetricsourceAutoscalingV2Beta2 {
  /**
   * name is the name of the resource in question.
   */
  name: string | null;
  /**
   * MetricTarget defines the target value, average value, or average utilization of a specific metric
   */
  target: {
    [k: string]: any;
  } | null;
}
