/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
 */
export interface Resourcequotaspec {
  /**
   * hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/
   */
  hard?: {
    [k: string]: any;
  } | null;
  /**
   * A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements.
   */
  scopeSelector?: {
    [k: string]: any;
  } | null;
  /**
   * A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.
   */
  scopes?: (string | null)[];
}
