/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RoleRef contains information that points to the role being used
 */
export interface Roleref {
  /**
   * APIGroup is the group for the resource being referenced
   */
  apiGroup: string | null;
  /**
   * Kind is the type of resource being referenced
   */
  kind: string | null;
  /**
   * Name is the name of resource being referenced
   */
  name: string | null;
}
