/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DEPRECATED.
 */
export interface RollbackconfigExtensionsV1Beta1 {
  /**
   * The revision to rollback to. If set to 0, rollback to the last revision.
   */
  revision?: number | null;
}
