/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.
 */
export interface RollingupdatestatefulsetstrategyAppsV1 {
  /**
   * Partition indicates the ordinal at which the StatefulSet should be partitioned. Default value is 0.
   */
  partition?: number | null;
}
