/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Spec to control the desired behavior of rolling update.
 */
export interface Rollingupdatedeployment {
  maxSurge?: (string | null) | (number | null);
  maxUnavailable?: (string | null) | (number | null);
}
