/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ScaleSpec describes the attributes of a scale subresource
 */
export interface ScalespecAppsV1Beta1 {
  /**
   * desired number of instances for the scaled object.
   */
  replicas?: number | null;
}
