/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ScaleIOVolumeSource represents a persistent ScaleIO volume
 */
export interface ScaleiovolumesourceV1 {
  /**
   * Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". Default is "xfs".
   */
  fsType?: string | null;
  /**
   * The host address of the ScaleIO API Gateway.
   */
  gateway: string | null;
  /**
   * The name of the ScaleIO Protection Domain for the configured storage.
   */
  protectionDomain?: string | null;
  /**
   * Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
   */
  readOnly?: boolean | null;
  /**
   * LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
   */
  secretRef: {
    [k: string]: any;
  } | null;
  /**
   * Flag to enable/disable SSL communication with Gateway, default false
   */
  sslEnabled?: boolean | null;
  /**
   * Indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned.
   */
  storageMode?: string | null;
  /**
   * The ScaleIO Storage Pool associated with the protection domain.
   */
  storagePool?: string | null;
  /**
   * The name of the storage system as configured in ScaleIO.
   */
  system: string | null;
  /**
   * The name of a volume already created in the ScaleIO system that is associated with this volume source.
   */
  volumeName?: string | null;
}
