/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements.
 */
export interface Scopeselector {
  /**
   * A list of scope selector requirements by scope of the resources.
   */
  matchExpressions?: ({
    [k: string]: any;
  } | null)[];
}
