/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SELinuxOptions are the labels to be applied to the container
 */
export interface Selinuxoptions {
  /**
   * Level is SELinux level label that applies to the container.
   */
  level?: string | null;
  /**
   * Role is a SELinux role label that applies to the container.
   */
  role?: string | null;
  /**
   * Type is a SELinux type label that applies to the container.
   */
  type?: string | null;
  /**
   * User is a SELinux user label that applies to the container.
   */
  user?: string | null;
}
