/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ServiceStatus represents the current status of a service.
 */
export interface ServicestatusV1 {
  /**
   * LoadBalancerStatus represents the status of a load-balancer.
   */
  loadBalancer?: {
    [k: string]: any;
  } | null;
}
