/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SessionAffinityConfig represents the configurations of session affinity.
 */
export interface Sessionaffinityconfig {
  /**
   * ClientIPConfig represents the configurations of Client IP based session affinity.
   */
  clientIP?: {
    [k: string]: any;
  } | null;
}
