/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SubjectAccessReviewStatus
 */
export interface SubjectaccessreviewstatusAuthorizationV1 {
  /**
   * Allowed is required. True if the action would be allowed, false otherwise.
   */
  allowed: boolean | null;
  /**
   * Denied is optional. True if the action would be denied, otherwise false. If both allowed is false and denied is false, then the authorizer has no opinion on whether to authorize the action. Denied may not be true if Allowed is true.
   */
  denied?: boolean | null;
  /**
   * EvaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request.
   */
  evaluationError?: string | null;
  /**
   * Reason is optional.  It indicates why a request was allowed or denied.
   */
  reason?: string | null;
}
