/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sysctl defines a kernel parameter to be set
 */
export interface SysctlV1 {
  /**
   * Name of a property to set
   */
  name: string | null;
  /**
   * Value of a property to set
   */
  value: string | null;
}
