/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * TCPSocketAction describes an action based on opening a socket
 */
export interface Tcpsocketaction {
  /**
   * Optional: Host name to connect to, defaults to the pod IP.
   */
  host?: string | null;
  port: (string | null) | (number | null);
}
