/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * TokenRequestSpec contains client provided parameters of a token request.
 */
export interface TokenrequestspecAuthenticationV1 {
  /**
   * Audiences are the intendend audiences of the token. A recipient of a token must identitfy themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences.
   */
  audiences: (string | null)[];
  /**
   * BoundObjectReference is a reference to an object that a token is bound to.
   */
  boundObjectRef?: {
    [k: string]: any;
  } | null;
  /**
   * ExpirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the 'expiration' field in a response.
   */
  expirationSeconds?: number | null;
}
