/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * TokenReviewSpec is a description of the token authentication request.
 */
export interface TokenreviewspecAuthenticationV1 {
  /**
   * Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
   */
  audiences?: (string | null)[];
  /**
   * Token is the opaque bearer token.
   */
  token?: string | null;
}
