/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UserInfo holds the information about the user needed to implement the user.Info interface.
 */
export interface UserinfoAuthenticationV1Beta1 {
  /**
   * Any additional information provided by the authenticator.
   */
  extra?: {
    [k: string]: any;
  } | null;
  /**
   * The names of groups this user is a part of.
   */
  groups?: (string | null)[];
  /**
   * A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
   */
  uid?: string | null;
  /**
   * The name that uniquely identifies this user among all active users.
   */
  username?: string | null;
}
