/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 */
export interface VolumeV1 {
  /**
   * Represents a Persistent Disk resource in AWS.
   *
   * An AWS EBS disk must exist before mounting to a container. The disk must also be in the same AWS zone as the kubelet. An AWS EBS disk can only be mounted as read/write once. AWS EBS volumes support ownership management and SELinux relabeling.
   */
  awsElasticBlockStore?: {
    [k: string]: any;
  } | null;
  /**
   * AzureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
   */
  azureDisk?: {
    [k: string]: any;
  } | null;
  /**
   * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
   */
  azureFile?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Ceph Filesystem mount that lasts the lifetime of a pod Cephfs volumes do not support ownership management or SELinux relabeling.
   */
  cephfs?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a cinder volume resource in Openstack. A Cinder volume must exist before mounting to a container. The volume must also be in the same region as the kubelet. Cinder volumes support ownership management and SELinux relabeling.
   */
  cinder?: {
    [k: string]: any;
  } | null;
  /**
   * Adapts a ConfigMap into a volume.
   *
   * The contents of the target ConfigMap's Data field will be presented in a volume as files using the keys in the Data field as the file names, unless the items element is populated with specific mappings of keys to paths. ConfigMap volumes support ownership management and SELinux relabeling.
   */
  configMap?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a source location of a volume to mount, managed by an external CSI driver
   */
  csi?: {
    [k: string]: any;
  } | null;
  /**
   * DownwardAPIVolumeSource represents a volume containing downward API info. Downward API volumes support ownership management and SELinux relabeling.
   */
  downwardAPI?: {
    [k: string]: any;
  } | null;
  /**
   * Represents an empty directory for a pod. Empty directory volumes support ownership management and SELinux relabeling.
   */
  emptyDir?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Fibre Channel volume. Fibre Channel volumes can only be mounted as read/write once. Fibre Channel volumes support ownership management and SELinux relabeling.
   */
  fc?: {
    [k: string]: any;
  } | null;
  /**
   * FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.
   */
  flexVolume?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Flocker volume mounted by the Flocker agent. One and only one of datasetName and datasetUUID should be set. Flocker volumes do not support ownership management or SELinux relabeling.
   */
  flocker?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Persistent Disk resource in Google Compute Engine.
   *
   * A GCE PD must exist before mounting to a container. The disk must also be in the same GCE project and zone as the kubelet. A GCE PD can only be mounted as read/write once or read-only many times. GCE PDs support ownership management and SELinux relabeling.
   */
  gcePersistentDisk?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a volume that is populated with the contents of a git repository. Git repo volumes do not support ownership management. Git repo volumes support SELinux relabeling.
   *
   * DEPRECATED: GitRepo is deprecated. To provision a container with a git repo, mount an EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir into the Pod's container.
   */
  gitRepo?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs volumes do not support ownership management or SELinux relabeling.
   */
  glusterfs?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a host path mapped into a pod. Host path volumes do not support ownership management or SELinux relabeling.
   */
  hostPath?: {
    [k: string]: any;
  } | null;
  /**
   * Represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.
   */
  iscsi?: {
    [k: string]: any;
  } | null;
  /**
   * Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   */
  name: string | null;
  /**
   * Represents an NFS mount that lasts the lifetime of a pod. NFS volumes do not support ownership management or SELinux relabeling.
   */
  nfs?: {
    [k: string]: any;
  } | null;
  /**
   * PersistentVolumeClaimVolumeSource references the user's PVC in the same namespace. This volume finds the bound PV and mounts that volume for the pod. A PersistentVolumeClaimVolumeSource is, essentially, a wrapper around another type of volume that is owned by someone else (the system).
   */
  persistentVolumeClaim?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Photon Controller persistent disk resource.
   */
  photonPersistentDisk?: {
    [k: string]: any;
  } | null;
  /**
   * PortworxVolumeSource represents a Portworx volume resource.
   */
  portworxVolume?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a projected volume source
   */
  projected?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Quobyte mount that lasts the lifetime of a pod. Quobyte volumes do not support ownership management or SELinux relabeling.
   */
  quobyte?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a Rados Block Device mount that lasts the lifetime of a pod. RBD volumes support ownership management and SELinux relabeling.
   */
  rbd?: {
    [k: string]: any;
  } | null;
  /**
   * ScaleIOVolumeSource represents a persistent ScaleIO volume
   */
  scaleIO?: {
    [k: string]: any;
  } | null;
  /**
   * Adapts a Secret into a volume.
   *
   * The contents of the target Secret's Data field will be presented in a volume as files using the keys in the Data field as the file names. Secret volumes support ownership management and SELinux relabeling.
   */
  secret?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a StorageOS persistent volume resource.
   */
  storageos?: {
    [k: string]: any;
  } | null;
  /**
   * Represents a vSphere volume resource.
   */
  vsphereVolume?: {
    [k: string]: any;
  } | null;
}
