/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * VolumeAttachmentSpec is the specification of a VolumeAttachment request.
 */
export interface Volumeattachmentspec {
  /**
   * Attacher indicates the name of the volume driver that MUST handle this request. This is the name returned by GetPluginName().
   */
  attacher: string | null;
  /**
   * The node that the volume should be attached to.
   */
  nodeName: string | null;
  /**
   * VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.
   */
  source: {
    [k: string]: any;
  } | null;
}
