/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Projection that may be projected along with other supported volume types
 */
export interface VolumeprojectionV1 {
  /**
   * Adapts a ConfigMap into a projected volume.
   *
   * The contents of the target ConfigMap's Data field will be presented in a projected volume as files using the keys in the Data field as the file names, unless the items element is populated with specific mappings of keys to paths. Note that this is identical to a configmap volume source without the default mode.
   */
  configMap?: {
    [k: string]: any;
  } | null;
  /**
   * Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
   */
  downwardAPI?: {
    [k: string]: any;
  } | null;
  /**
   * Adapts a secret into a projected volume.
   *
   * The contents of the target Secret's Data field will be presented in a projected volume as files using the keys in the Data field as the file names. Note that this is identical to a secret volume source without the default mode.
   */
  secret?: {
    [k: string]: any;
  } | null;
  /**
   * ServiceAccountTokenProjection represents a projected service account token volume. This projection can be used to insert a service account token into the pods runtime filesystem for use against APIs (Kubernetes API Server or otherwise).
   */
  serviceAccountToken?: {
    [k: string]: any;
  } | null;
}
