/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * WebhookConversion describes how to call a conversion webhook
 */
export interface WebhookconversionApiextensionsV1 {
  /**
   * WebhookClientConfig contains the information to make a TLS connection with the webhook.
   */
  clientConfig?: {
    [k: string]: any;
  } | null;
  /**
   * conversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail.
   */
  conversionReviewVersions: (string | null)[];
}
